[package]
name = "button_component"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { workspace = true, features = [
    "wayland",
    "x11",
    "font-kit",
    "windows-manifest",
] }
gpui_macros.workspace = true