[workspace]
resolver = "2"
members = [
    "crates/hello_world",
    "crates/likes_counter",
    "crates/button_component",
    "crates/action_keybindings",
]

[workspace.dependencies]
gpui = { version = "0.2.0", default-features = false }
gpui-macros = "0.2.0"
